import React from "react";
import {
  X,
  FileText,
  Printer,
  Download,
  Building2,
  Calendar,
  CheckCircle2,
  TrendingDown,
  ShieldCheck,
  Zap,
} from "lucide-react";
import { AgentContext } from "../agent/orchestrator";

interface AuditReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  context: AgentContext;
}

export const AuditReportModal: React.FC<AuditReportModalProps> = ({
  isOpen,
  onClose,
  context,
}) => {
  if (!isOpen) return null;

  const { facility, anomalyReport, investigation, solutions, chosenSolution, verification } = context;
  const config = facility.config;
  const symbol = config.currency_symbol;
  const solC = solutions?.C;
  const currentKwh = anomalyReport?.actual_kwh ?? facility.current_kwh;
  const baselineKwh = anomalyReport?.baseline_kwh ?? facility.baseline_kwh;
  const varianceKwh = anomalyReport?.variance_kwh ?? currentKwh - baselineKwh;
  const variancePct = anomalyReport?.variance_pct ?? Number(((varianceKwh / baselineKwh) * 100).toFixed(1));
  const annualEnergyAvoidedKwh = solC ? solC.estimated_saving_kwh * 365 : null;
  const annualCo2OffsetKg = solC
    ? Math.round(solC.estimated_saving_kwh * 365 * config.co2_factor_kg_per_kwh)
    : null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-emerald-400" />
            <div>
              <h3 className="text-sm font-bold text-white">
                Executive Energy Audit & Digital Twin Verification Brief
              </h3>
              <p className="text-[11px] text-slate-400">
                Generated by EnerQ AI Energy Agent • Audit Reference: ENERQ-{new Date().toISOString().slice(0, 7).replace("-", "")}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable / Viewable Report Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs text-slate-300 font-sans leading-relaxed">
          {/* Facility Header Section */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="text-[10px] uppercase font-bold tracking-wider text-emerald-400">
                Target Facility
              </div>
              <h4 className="text-base font-bold text-white mt-0.5">{config.name}</h4>
              <p className="text-slate-400 text-xs mt-0.5">
                {config.type} • {config.location} • Area: {config.area_sqm} m²
              </p>
            </div>

            <div className="text-left sm:text-right space-y-0.5 text-xs">
              <div>
                <span className="text-slate-500">Working Hours:</span>{" "}
                <span className="text-slate-200 font-medium">
                  {config.working_hours.start} – {config.working_hours.end}
                </span>
              </div>
              <div>
                <span className="text-slate-500">Tariff Rate:</span>{" "}
                <span className="text-slate-200 font-medium">
                  {symbol}{config.electricity_rate} / kWh
                </span>
              </div>
              <div>
                <span className="text-slate-500">Status:</span>{" "}
                <span className="text-emerald-400 font-bold">
                  {verification ? "Verified Optimized" : "Autonomous Anomaly Identified"}
                </span>
              </div>
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div>
            <h5 className="text-xs font-bold text-white uppercase tracking-wider mb-2 text-slate-200 border-b border-slate-800 pb-1">
              1. Executive Summary & Diagnostic Finding
            </h5>
            <p className="text-slate-300">
              EnerQ autonomously observed daily consumption of <strong className="text-white">{currentKwh} kWh/day</strong>, representing a <strong className="text-amber-400">+{variancePct}% anomaly (+{varianceKwh} kWh excess)</strong> over the seasonal baseline of {baselineKwh} kWh/day.
            </p>
            <p className="mt-2 text-slate-300">
              Sub-meter telemetry pinpointed that the 20 kW Central HVAC AHU chiller system operated 4 continuous hours past the 18:00 facility closing schedule (18:00–22:00), accounting for 80 kWh of direct energy waste. Concurrently, 38 unmanaged workstation circuits drew 13-15 kWh of idle power outside working hours.
            </p>
          </div>

          {/* Section 2: Multi-Criteria Scenarios */}
          <div>
            <h5 className="text-xs font-bold text-white uppercase tracking-wider mb-2 text-slate-200 border-b border-slate-800 pb-1">
              2. Digital Twin Simulated Solutions Matrix
            </h5>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border border-slate-800">
                <thead className="bg-slate-950 text-slate-400 font-semibold">
                  <tr>
                    <th className="p-2 border-b border-slate-800">Option</th>
                    <th className="p-2 border-b border-slate-800">Intervention</th>
                    <th className="p-2 border-b border-slate-800">Daily kWh</th>
                    <th className="p-2 border-b border-slate-800">Reduction</th>
                    <th className="p-2 border-b border-slate-800">Monthly Recapture</th>
                    <th className="p-2 border-b border-slate-800">Risk / Score</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  <tr className="hover:bg-slate-800/30">
                    <td className="p-2 font-bold text-slate-300">A</td>
                    <td className="p-2">HVAC 18:00 Schedule Cutoff</td>
                    <td className="p-2">{solutions?.A.simulated_daily_kwh} kWh</td>
                    <td className="p-2 text-emerald-400 font-semibold">-{solutions?.A.estimated_saving_pct}% ({solutions?.A.estimated_saving_kwh} kWh)</td>
                    <td className="p-2">{symbol}{solutions?.A.monthly_cost_saving}</td>
                    <td className="p-2">{solutions?.A.risk_level} ({solutions?.A.decision_score}/100)</td>
                  </tr>
                  <tr className="hover:bg-slate-800/30">
                    <td className="p-2 font-bold text-slate-300">B</td>
                    <td className="p-2">Thermostat Offset (+1.5°C)</td>
                    <td className="p-2">{solutions?.B.simulated_daily_kwh} kWh</td>
                    <td className="p-2 text-teal-400 font-semibold">-{solutions?.B.estimated_saving_pct}% ({solutions?.B.estimated_saving_kwh} kWh)</td>
                    <td className="p-2">{symbol}{solutions?.B.monthly_cost_saving}</td>
                    <td className="p-2">{solutions?.B.risk_level} ({solutions?.B.decision_score}/100)</td>
                  </tr>
                  <tr className="bg-emerald-950/40 font-semibold text-white">
                    <td className="p-2 text-emerald-400 font-bold">C (Best)</td>
                    <td className="p-2">Combined HVAC Cutoff + Idle Sleep</td>
                    <td className="p-2">{solC?.simulated_daily_kwh} kWh</td>
                    <td className="p-2 text-emerald-400 font-bold">-{solC?.estimated_saving_pct}% ({solC?.estimated_saving_kwh} kWh)</td>
                    <td className="p-2 font-bold text-emerald-300">{symbol}{solC?.monthly_cost_saving}</td>
                    <td className="p-2 text-emerald-400 font-bold">{solC?.risk_level} ({solC?.decision_score}/100)</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Recommended Action Plan */}
          <div>
            <h5 className="text-xs font-bold text-white uppercase tracking-wider mb-2 text-slate-200 border-b border-slate-800 pb-1">
              3. Recommended Implementation Roadmap
            </h5>
            <ol className="list-decimal list-inside space-y-1.5 text-slate-300">
              <li>
                <strong>BMS Calendar Override</strong>: Update central chiller schedule to automatically switch to night setback at 18:00 Monday–Friday.
              </li>
              <li>
                <strong>Smart PDU Relay Automation</strong>: Schedule workstation non-critical plug load sleep policy for 18:15.
              </li>
              <li>
                <strong>Occupancy Motion Fallback</strong>: Allow manual 1-hour push-button cooling overrides for authenticated overtime workers.
              </li>
              <li>
                <strong>Autonomous Verification</strong>: EnerQ Agent continuously verifies 24-hour load profile daily at 18:05 EET.
              </li>
            </ol>
          </div>

          {/* Section 4: Verified ROI Summary */}
          <div className="p-4 rounded-xl bg-emerald-950/50 border border-emerald-500/40 flex flex-wrap items-center justify-between gap-3 text-xs">
            <div>
              <div className="text-emerald-300 font-bold uppercase text-[10px] tracking-wider">
                Total Annual Value Recaptured
              </div>
              <div className="text-xl font-extrabold text-white mt-0.5">
                {symbol}{solC?.annual_cost_saving} / year
              </div>
            </div>

            <div>
              <div className="text-slate-400 font-medium uppercase text-[10px] tracking-wider">
                Annual Energy Avoided
              </div>
              <div className="text-lg font-bold text-emerald-400 mt-0.5">
                {annualEnergyAvoidedKwh?.toLocaleString() ?? "—"} kWh / year
              </div>
            </div>

            <div>
              <div className="text-slate-400 font-medium uppercase text-[10px] tracking-wider">
                CO₂ Emissions Offset
              </div>
              <div className="text-lg font-bold text-teal-300 mt-0.5">
                {annualCo2OffsetKg?.toLocaleString() ?? "—"} kg CO₂ / year
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between text-xs">
          <span className="text-slate-500">
            EnerQ Autonomous Energy Agent Platform • Zero Unsolicited Feature Scope
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-white transition-colors"
          >
            Close Brief
          </button>
        </div>
      </div>
    </div>
  );
};
